backend:
  name: github
  repo: VHAAntimicrobialStewardship/VHAAntimicrobialStewardship.github.io
  branch: main
  base_url: https://sveltia-cms-auth.androo-holbrook.workers.dev
  client_id: Ov23li1V4m6vxpldbI3O
  client_secret: 23bb86389d5917142b5c28ca7e361f1d3dcf5c6e

publish_mode: simple
site_url: https://VHAAntimicrobialStewardship.github.io/
display_url: https://VHAAntimicrobialStewardship.github.io/
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
editor:
  preview: false

collections:
  - label: "Antibiotic Links"
    name: "abx_links"
    files:
      - label: "Antibiotic Links"
        name: "abx_links"
        file: "cms-data/abx-links.cms.json"
        format: "json"
        extension: "json"
        fields:
          - label: "Entries"
            name: "entries"
            widget: list
            fields:
              - { label: "Name", name: "Name", widget: "string", required: false }
              - { label: "URL", name: "URL", widget: "string", required: false }
              - { label: "Route Filter", name: "RouteFilter", widget: "string", required: false }
  - label: "Sinusitis Test Tree"
    name: "sinusitis_test_tree"
    files:
      - label: "Sinusitis Test Tree"
        name: "sinusitis_test_tree"
        file: "stations/001-TestStation/SinusitisTestOMJSON.json"
        format: "json"
        extension: "json"
        fields:
          - label: "Menus"
            name: "menus"
            widget: list
            identifier_field: Name
            fields:
              - { label: "Name", name: "Name", widget: "string" }
              - { label: "Term 1", name: "Term1", widget: "string", required: false }
              - { label: "Term 2", name: "Term2", widget: "string", required: false }
              - { label: "Text Body", name: "Text", widget: "markdown", required: false }
              - label: "Link Targets"
                name: "LinkTargets"
                widget: list
                required: false
                fields:
                  - { label: "Key", name: "Key", widget: "string" }
                  - { label: "Link Text", name: "Text", widget: "string", required: false }
                  - { label: "Target Item", name: "Item", widget: "string" }
  - label: "Site Settings"
    name: "site_settings"
    files:
      - label: "Web Manifest"
        name: "web_manifest"
        file: "manifest.webmanifest"
        format: "json"
        extension: "json"
        identifier_field: name
        summary: "{{name}}"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Short Name", name: "short_name", widget: "string"}
          - {label: "Description", name: "description", widget: "string", required: false}
          - {label: "Scope", name: "scope", widget: "string"}
          - {label: "Start URL", name: "start_url", widget: "string"}
          - {label: "Background Color", name: "background_color", widget: "string"}
          - {label: "Theme Color", name: "theme_color", widget: "string"}
          - {label: "Display", name: "display", widget: "string"}
          - label: "Icons"
            name: "icons"
            widget: list
            fields:
              - {label: "Src", name: "src", widget: "string"}
              - {label: "Sizes", name: "sizes", widget: "string"}
              - {label: "Type", name: "type", widget: "string"}
              - {label: "Purpose", name: "purpose", widget: "string", required: false}
